# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CURT
                                 A QGIS plugin
 GENERAR_CURT
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-31
        git sha              : $Format:%H$
        copyright            : (C) 2023 by ioshimar.rodriguez
        email                : ioshimar.rodriguez@inegi.org.mx
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from osgeo import ogr
from osgeo import osr
from osgeo import gdal
from qgis._core import QgsFeatureRequest
from shapely.wkt import loads
from qgis.core import QgsVectorLayer, QgsFeature, QgsField, QgsGeometry, QgsPointXY, QgsField, QgsProject, edit
from qgis.utils import iface
from datetime import datetime
import operator
from qgis.core import Qgis
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QDialog
from qgis.core import QgsProject
from PyQt5.QtGui import QIcon, QFileOpenEvent
import os
from pathlib import Path
import math
#import processing


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .GENERAR_CURT_dialog import CURTDialog
import os.path


class CURT:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CURT_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GENERAR_CURT')

        # Check if plugin was started the first time in current QGIS session
        #self.actionOpen.triggered.connect(self.openFile)
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None




    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CURT', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/GENERAR_CURT/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Procesamiento para generar la CURT'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GENERAR_CURT'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Selecciona un archivo ", "", '*.shp')
        self.dlg.lineEdit.setText(filename)


    def run(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started

        #dlg.lineEdit.clear()  # clear text in lineEdit object
        #dlg.pushButton.clicked.connect(dlg.select_output_file)


        if self.first_start == True:
            self.first_start = False
            self.dlg = CURTDialog()
            self.dlg.actionOpen.clicked.connect(self.select_output_file)

        # Fetch the currently loaded layers
        #layers = QgsProject.instance().layerTreeRoot().children()
        # Clear the contents of the comboBox from previous runs
        self.dlg.lineEdit.clear()
        #self.dlg.actionOpen.clicked.connect(self.select_output_file)
        # Populate the comboBox with names of all the loaded layers
        #self.dlg.comboBox.addItems([layer.name() for layer in layers])

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            filename = self.dlg.lineEdit.text()
           
            path = '' + filename + ''

            rut = os.path.basename(path)
            tabla = Path(rut).stem

            # Obtener el proyecto actual de QGIS
            project = QgsProject.instance()

            # Buscar la capa en el proyecto por su nombre
            layer = project.mapLayersByName(tabla)
            if layer:
                # Quitar la capa del proyecto
                project.removeMapLayer(layer[0])

            #QMessageBox.information(iface.mainWindow(), "ESTRUCTURA FALLIDA", '' + path + '')

            dataSource1 = ogr.Open(path, 1)
            # dataSource2 = ogr.Open(path, 1)



            layer = dataSource1.GetLayer()
            # layer2= dataSource2.GetLayer()
            layerDefinition = layer.GetLayerDefn()

            # Prepare a transformation between projections
            src_srs = layer.GetSpatialRef()
            epsg = src_srs.GetAttrValue('AUTHORITY', 1)
            tgt_srs = osr.SpatialReference()
            tgt_srs.ImportFromEPSG(3857)
            transform = osr.CoordinateTransformation(src_srs, tgt_srs)

            def cargar_layer():
               vlayer = QgsVectorLayer(path, tabla, "ogr")
               QgsProject.instance().addMapLayer(vlayer)

            def valdupli():
                dataSource2 = ogr.Open(path, 1)
                layer2 = dataSource2.GetLayer()
                for feature in layer:
                    geoma = feature.GetGeometryRef()
                    if geoma is not None:
                        for featureb in layer2:
                            geomb = featureb.GetGeometryRef()
                            if geomb is not None:
                                res = geoma.Equals(geomb)
                                if res and (feature.GetFID() != featureb.GetFID()):
                                    notas = feature.GetFieldIndex("notas12a")
                                    feature.SetField(notas, '12a,')
                                    layer.SetFeature(feature)
                dataSource1 = dataSource2 = None

            """
            def caracteres():
                for feature in layer:
                    id_cat = feature.GetField("id_cat")
                    ida = str(id_cat)
                    if (id_cat is not None) or (id_cat != ''):
                        caracter = any(c != '-' and not c.isalnum() for c in id_cat)
                        if caracter:
                            notas = feature.GetFieldIndex("notas21")
                            feature.SetField(notas, '21,')
                            layer.SetFeature(feature)
            """

            def caracteres():
                for feature in layer:
                    id_cat = feature.GetField("id_cat")

                    # Verificar si id_cat es válido antes de realizar la comprobación de caracteres
                    if id_cat is not None:
                        # Convertir id_cat en una cadena para manejar valores que no son None
                        id_cat_str = str(id_cat)

                        if id_cat_str != '':
                            # Realizar la verificación de caracteres solo si id_cat no está vacío
                            caracter = any(c != '-' and not c.isalnum() for c in id_cat_str)
                            if caracter:
                                notas = feature.GetFieldIndex("notas21")
                                feature.SetField(notas, '21,')
                                layer.SetFeature(feature)

            def dup_cve():
                capa = QgsVectorLayer(path, "curt", "ogr")
                # capa.dataProvider().addAttributes([QgsField('igual_cve',  QVariant.String)])

                with edit(capa):
                    registros = capa.getFeatures()
                    for registro in registros:
                        id_actual = registro.id()
                        clave_actual = registro['id_cat']
                        ids = str(clave_actual)
                        # print(clave_actual)
                        if (clave_actual != None ):
                            idc = ids.isalnum()
                            if (idc == True):

                                expresion_filtro = 'id_cat=\'' + clave_actual + '\''

                                request = QgsFeatureRequest().setFilterExpression(expresion_filtro)

                                for feature in capa.getFeatures(request):
                                    id_compara = feature.id()
                                    if (id_actual != id_compara):
                                        registro.setAttribute(registro.fieldNameIndex('notas14'), '14,')
                                        capa.updateFeature(registro)
                                        feature.setAttribute(feature.fieldNameIndex('notas14'), '14,')
                                        capa.updateFeature(feature)

            def area_menor():
                for feature in layer:
                    geom = feature.GetGeometryRef()
                    if geom is not None:
                        geom2 = geom.Clone()
                        geom2.Transform(transform)

                        area_in_sq_m = geom2.GetArea()
                        area_in_sq_km = area_in_sq_m / 1000000
                        # print('Area in sq m: ', area_in_sq_m)
                        # print('Area in sq km: ', area_in_sq_km)
                        if area_in_sq_m < 1:
                            notas = feature.GetFieldIndex("notas15")
                            feature.SetField(notas, '15,')
                            layer.SetFeature(feature)
                    else:
                        # Manejar caso de geom=None aquí si es necesario
                        pass

                # dataSource1.Destroy()

            def geom_nula():
                for feature in layer:
                    geom = feature.GetGeometryRef()
                    if geom is None:
                        # Manejar caso de geometría nula
                        notas = feature.GetFieldIndex("notas10a")
                        feature.SetField(notas, '10a,')  # Nota indicando geometría nula
                        layer.SetFeature(feature)
                    else:
                        nulo = geom.IsEmpty()
                        if nulo:
                            notas = feature.GetFieldIndex("notas10a")
                            feature.SetField(notas, '10a,')
                            layer.SetFeature(feature)

            def geom_valida():
                for feature in layer:
                    geom = feature.GetGeometryRef()
                    if geom is not None:
                        if not geom.IsValid():
                            notas = feature.GetFieldIndex("notas10")
                            feature.SetField(notas, '10,')
                            layer.SetFeature(feature)
                    else:
                        # Manejar caso de geom=None aquí si es necesario
                        pass

            def valtraslape():
                dataSource2 = ogr.Open(path, 1)
                layer2 = dataSource2.GetLayer()
                for feature in layer:
                    geoma = feature.GetGeometryRef()
                    if geoma is not None:
                        for featureb in layer2:
                            geomb = featureb.GetGeometryRef()
                            if geomb is not None:
                                res = geoma.Overlaps(geomb)
                                if res and (feature.GetFID() != featureb.GetFID()):
                                    notas = feature.GetFieldIndex("notas11a")
                                    feature.SetField(notas, '11a,')
                                    layer.SetFeature(feature)
                dataSource1 = dataSource2 = None

            def crear_campos():
                ncamp = []

                for i in range(layerDefinition.GetFieldCount()):
                    fdefn = layerDefinition.GetFieldDefn(i)
                    ncamp.append(fdefn.name)
                if ("curt" in ncamp):
                    inde = ncamp.index("curt")
                    layer.DeleteField(inde)
                    nameField = ogr.FieldDefn('curt',
                                              ogr.OFTString)  # create new field of type string called Name to store the country names
                    nameField.SetWidth(21)
                    layer.CreateField(nameField)
                else:
                    nameField = ogr.FieldDefn('curt',
                                              ogr.OFTString)  # create new field of type string called Name to store the country names
                    nameField.SetWidth(21)
                    layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas1',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas2',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas3',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas4',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas5',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas6',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas7',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas8',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas11a',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas10',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas10a',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas15',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas14',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas21',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)
                nameField = ogr.FieldDefn('notas12a',
                                          ogr.OFTString)  # create new field of type string called Name to store the country names
                layer.CreateField(nameField)

            def valcve_ent():
                for campos in layer:
                    if (campos.GetField("cve_ent") == '') or (campos.GetField("cve_ent") is None):
                        notas = campos.GetFieldIndex("notas1")
                        campos.SetField(notas, '1,')
                        layer.SetFeature(campos)
                    if (operator.length_hint(campos.GetField("cve_ent")) != 2):
                        notas = campos.GetFieldIndex("notas2")
                        campos.SetField(notas, '2,')
                        layer.SetFeature(campos)

            def valcve_mun():
                for campos in layer:
                    if (campos.GetField("cve_mun") == '') or (campos.GetField("cve_mun") is None):
                        notas = campos.GetFieldIndex("notas3")
                        campos.SetField(notas, '3,')
                        layer.SetFeature(campos)
                    if (operator.length_hint(campos.GetField("cve_mun")) != 3):
                        notas = campos.GetFieldIndex("notas4")
                        campos.SetField(notas, '4,')
                        layer.SetFeature(campos)

            def valcve_loc():
                for campos in layer:
                    if (campos.GetField("cve_loc") == '') or (campos.GetField("cve_loc") is None):
                        notas = campos.GetFieldIndex("notas5")
                        campos.SetField(notas, '5,')
                        layer.SetFeature(campos)
                    if (operator.length_hint(campos.GetField("cve_loc")) != 4):
                        notas = campos.GetFieldIndex("notas6")
                        campos.SetField(notas, '6,')
                        layer.SetFeature(campos)

            def valid_cat():
                for campos in layer:
                    if (campos.GetField("id_cat") == '') or (campos.GetField("id_cat") is None):
                        notas = campos.GetFieldIndex("notas7")
                        campos.SetField(notas, '7,')
                        layer.SetFeature(campos)

            def valgeom():
                for campos in layer:
                    geom = campos.GetGeometryRef()
                    if geom is not None:
                        typegeom = geom.GetGeometryName()
                        if typegeom != "POLYGON" and typegeom != "MULTIPOLYGON":
                            notas = campos.GetFieldIndex("notas8")
                            campos.SetField(notas, '9,')
                            layer.SetFeature(campos)

            def concat_field():
                ncampn = []

                for i in range(layerDefinition.GetFieldCount()):
                    fdefn = layerDefinition.GetFieldDefn(i)
                    ncampn.append(fdefn.name)
                if ("notas" in ncampn):
                    inden = ncampn.index("notas")
                    layer.DeleteField(inden)
                    nameField = ogr.FieldDefn('notas',
                                              ogr.OFTString)  # create new field of type string called Name to store the country names
                    layer.CreateField(nameField)
                    for campos in layer:
                        if (campos.GetField("notas1") == None):
                            n1 = ''
                            # print(n1)
                        else:
                            n1 = campos.GetField("notas1")
                        if (campos.GetField("notas2") == None):
                            n2 = ''

                        else:
                            n2 = campos.GetField("notas2")
                        if (campos.GetField("notas3") == None):
                            n3 = ''

                        else:
                            n3 = campos.GetField("notas3")
                        if (campos.GetField("notas4") == None):
                            n4 = ''

                        else:
                            n4 = campos.GetField("notas4")
                        if (campos.GetField("notas5") == None):
                            n5 = ''

                        else:
                            n5 = campos.GetField("notas5")
                        if (campos.GetField("notas6") == None):
                            n6 = ''

                        else:
                            n6 = campos.GetField("notas6")
                        if (campos.GetField("notas7") == None):
                            n7 = ''

                        else:
                            n7 = campos.GetField("notas7")
                        if (campos.GetField("notas8") == None):
                            n8 = ''

                        else:
                            n8 = campos.GetField("notas8")

                        if (campos.GetField("notas11a") == None):
                            n11 = ''

                        else:
                            n11 = campos.GetField("notas11a")
                        if (campos.GetField("notas10") == None):
                            n10 = ''

                        else:
                            n10 = campos.GetField("notas10")

                        if (campos.GetField("notas10a") == None):
                            n10a = ''

                        else:
                            n10a = campos.GetField("notas10a")

                        if (campos.GetField("notas15") == None):
                            n15 = ''

                        else:
                            n15 = campos.GetField("notas15")

                        if (campos.GetField("notas14") == None):
                            n14 = ''

                        else:
                            n14 = campos.GetField("notas14")

                        if (campos.GetField("notas21") == None):
                            n21 = ''

                        else:
                            n21 = campos.GetField("notas21")

                        if (campos.GetField("notas12a") == None):
                            n12 = ''

                        else:
                            n12 = campos.GetField("notas12a")

                        nota = ''.join([n1, n2, n3, n4, n5, n6, n7, n8, n10, n10a, n11, n12, n14, n15, n21])
                        notas = campos.GetFieldIndex("notas")
                        campos.SetField(notas, nota)
                        layer.SetFeature(campos)
                        # print(nota)
                else:
                    nameField = ogr.FieldDefn('notas',
                                              ogr.OFTString)  # create new field of type string called Name to store the country names
                    layer.CreateField(nameField)
                    for campos in layer:
                        if (campos.GetField("notas1") == None):
                            n1 = ''
                            # print(n1)
                        else:
                            n1 = campos.GetField("notas1")
                        if (campos.GetField("notas2") == None):
                            n2 = ''

                        else:
                            n2 = campos.GetField("notas2")
                        if (campos.GetField("notas3") == None):
                            n3 = ''

                        else:
                            n3 = campos.GetField("notas3")
                        if (campos.GetField("notas4") == None):
                            n4 = ''

                        else:
                            n4 = campos.GetField("notas4")
                        if (campos.GetField("notas5") == None):
                            n5 = ''

                        else:
                            n5 = campos.GetField("notas5")
                        if (campos.GetField("notas6") == None):
                            n6 = ''

                        else:
                            n6 = campos.GetField("notas6")
                        if (campos.GetField("notas7") == None):
                            n7 = ''

                        else:
                            n7 = campos.GetField("notas7")
                        if (campos.GetField("notas8") == None):
                            n8 = ''

                        else:
                            n8 = campos.GetField("notas8")

                        if (campos.GetField("notas11a") == None):
                            n11 = ''

                        else:
                            n11 = campos.GetField("notas11a")
                        if (campos.GetField("notas10") == None):
                            n10 = ''

                        else:
                            n10 = campos.GetField("notas10")

                        if (campos.GetField("notas10a") == None):
                            n10a = ''

                        else:
                            n10a = campos.GetField("notas10a")

                        if (campos.GetField("notas15") == None):
                            n15 = ''

                        else:
                            n15 = campos.GetField("notas15")

                        if (campos.GetField("notas14") == None):
                            n14 = ''

                        else:
                            n14 = campos.GetField("notas14")

                        if (campos.GetField("notas21") == None):
                            n21 = ''

                        else:
                            n21 = campos.GetField("notas21")

                        if (campos.GetField("notas12a") == None):
                            n12 = ''

                        else:
                            n12 = campos.GetField("notas12a")

                        nota = ''.join([n1, n2, n3, n4, n5, n6, n7, n8, n10, n10a, n11, n12, n14, n15, n21])
                        notas = campos.GetFieldIndex("notas")
                        campos.SetField(notas, nota)
                        layer.SetFeature(campos)
                        # print(nota)

            def gen_curt():

                def decimal_a_sexagesimal(coordenada_decimal):
                    coordenada_decimal = abs(coordenada_decimal)

                    # Se convierte coordenada a formato sexagesimal
                    grados = int(coordenada_decimal)
                    minutos_decimal = (coordenada_decimal - grados) * 60
                    minutos = int(minutos_decimal)
                    segundos_decimal = (minutos_decimal - minutos) * 60
                    segundos = int(segundos_decimal)
                    segundos_mod = segundos_decimal % 1
                    centesimas = int(segundos_mod * 10000)

                    # Se valida las partes de la coordenada en formato sexagesimal
                    fraccion_seg = int(str(math.trunc(segundos_mod * 100000))[-1])
                    if (fraccion_seg >= 6) and (fraccion_seg <= 9):
                        centesimas += 1
                    elif fraccion_seg == 5 and (centesimas % 2 == 1):
                        centesimas += 1

                    if (centesimas >= 10000):
                        segundos += 1
                        centesimas = 0

                    if segundos >= 60:
                        minutos += 1
                    if minutos >= 60:
                        grados += 1

                    # Se formatean las partes de la coordenada para cumplir con la especificación de la CURT
                    g = str(grados).zfill(2)
                    if (grados > 90):
                        g = str(grados).zfill(3)
                    m = str(minutos).zfill(2)
                    s = str(segundos).zfill(2)
                    c = str(centesimas).zfill(4)

                    return f'{g}{m}{s}{c}'

                campo_curt = "curt"
                contador = 0
                registros_nulos = False

                for campos in layer:
                    if (campos.GetField("notas") == '') or (campos.GetField("notas") is None):
                        geom = campos.GetGeometryRef()
                        if geom is not None:
                            # pt = loads(geom.ExportToWkt()).centroid
                            # Obtiene las coordenadas de un punto en el polígono (representative_point)
                            point = loads(geom.ExportToWkt()).representative_point()
                            longi = -point.x
                            latitu = point.y

                            # Utiliza la función para calcular las coordenadas CURT
                            latitud_curt = decimal_a_sexagesimal(latitu)
                            longitud_curt = decimal_a_sexagesimal(longi)

                            CURT_conc = latitud_curt + longitud_curt

                            campos.SetField('curt', CURT_conc)  # Asigna el valor calculado a 'curt'

                            layer.SetFeature(campos)

                            if not registros_nulos:
                                registros_nulos = True
                        else:
                            # Manejar el caso donde geom es None, si es necesario
                            pass

                    contador += 1
                # Imprime el total de registros procesados
                print("Total de registros procesados:", contador)

                # Verifica si hay registros nulos en 'curt'
                if registros_nulos:
                    for feature in layer:
                        valor_curt = feature.GetField(campo_curt)
                        notas = feature.GetField("notas")
                        id_cat = feature.GetField("id_cat")

                        if ((not valor_curt or valor_curt == "") and (not notas or notas == "")) and id_cat:
                            geom = feature.GetGeometryRef()
                            if geom is not None:
                                pt = loads(geom.ExportToWkt()).representative_point()  # Igual a Point On Surface
                                longi = -pt.x
                                latitu = pt.y

                                # Utiliza la función para calcular las coordenadas CURT
                                latitud_curt = decimal_a_sexagesimal(latitu)
                                longitud_curt = decimal_a_sexagesimal(longi)

                                curt = latitud_curt + longitud_curt

                                # Asigna el valor calculado a 'curt'
                                feature.SetField(campo_curt, curt)

                                # Actualiza el registro en la capa de datos
                                if layer.SetFeature(feature) != 0:
                                    print("Error al asignar valor a 'curt' en el registro con ID_CAT:", id_cat)
                                else:
                                    print("Se asignó el valor calculado a 'curt' en el registro con ID_CAT:", id_cat)
                            else:
                                # Manejar el caso donde geom es None, si es necesario
                                pass


            def delete_field():
                # print("entre")
                ds = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas1')
                ds2 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds2.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas2')
                ds3 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds3.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas3')
                ds4 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds4.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas4')
                ds5 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds5.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas5')
                ds6 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds6.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas6')
                ds7 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds7.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas7')
                ds8 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds8.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas8')
                ds11a = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds11a.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas11a')
                ds10 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds10.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas10')
                ds10a = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds10a.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas10a')
                ds15 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds15.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas15')
                ds14 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds14.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas14')
                ds21 = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds21.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas21')
                ds12a = gdal.OpenEx(path, gdal.OF_VECTOR | gdal.OF_UPDATE)
                ds12a.ExecuteSQL('ALTER TABLE ' + tabla + ' DROP COLUMN notas12a')

            now = datetime.now()
            current_time = now.strftime("%H:%M:%S")
            print("Inicio proceso=", current_time)

            if epsg == '6365' or epsg == '4326':

                # print ("     ¡validando estructura!       ")
                # iface.messageBar().pushMessage("¡validando estructura!", level=Qgis.Success)

                count_field = layerDefinition.GetFieldCount()
                # VALIDO QUE NO SEA MAYOR A Y CAMPOS DE LA ESTRUCTURA
                # if(count_field>4):
                # print("El shape contiene mas de los campos necesarios, revisa la NORMA")
                #        QMessageBox.information(iface.mainWindow(), "PROCESO", 'El shape contiene mas de los campos necesarios, revisa la NORMA (cve_ent,cve_mun,cve_loc,id_cat) ')
                # else:
                nombre = []
                tipo = []
                wid = []
                for i in range(layerDefinition.GetFieldCount()):
                    fdefn = layerDefinition.GetFieldDefn(i)
                    nombre.append(fdefn.name)
                    fieldTypeCode = layerDefinition.GetFieldDefn(i).GetType()
                    fieldType = layerDefinition.GetFieldDefn(i).GetFieldTypeName(fieldTypeCode)
                    tipo.append(fieldType)
                    fieldWidth = layerDefinition.GetFieldDefn(i).GetWidth()
                    wid.append(fieldWidth)
                # VALIDO ESTRUCTURA DE CAMPOS
                if ("cve_ent" in nombre) and ("cve_mun" in nombre) and ("cve_loc" in nombre) and ("id_cat" in nombre):
                    # print("estructura incorrecta")
                    i_cve_ent = nombre.index("cve_ent")
                    i_cve_mun = nombre.index("cve_mun")
                    i_cve_loc = nombre.index("cve_loc")
                    i_id_cat = nombre.index("id_cat")
                    if (tipo[i_cve_ent] == "String") and (tipo[i_cve_mun] == "String") and (
                            tipo[i_cve_loc] == "String") and (tipo[i_id_cat] == "String"):
                        if (wid[i_cve_ent] == 2) and (wid[i_cve_mun] == 3) and (wid[i_cve_loc] == 4) and (
                                wid[i_id_cat] == 35):
                            # print ("     ¡validando informacion!       ")
                            # iface.messageBar().pushMessage("¡validando información!", level=Qgis.Success)
                            # revisar_campo_curt()
                            crear_campos()
                            valcve_ent()
                            valcve_mun()
                            valcve_loc()
                            valid_cat()
                            valgeom()
                            geom_valida()
                            geom_nula()
                            valtraslape()
                            valdupli()
                            area_menor()
                            caracteres()
                            dup_cve()
                            concat_field()
                            # print ("     ¡generando CURT!       ")
                            # iface.messageBar().pushMessage("¡generando CURT!", level=Qgis.Success)
                            gen_curt()
                            delete_field()
                            cargar_layer()

                            now = datetime.now()
                            current_time = now.strftime("%H:%M:%S")
                            print("Termino proceso :", current_time)
                            # iface.messageBar().pushMessage("El procesamiento a terminado, revise su shape", level=Qgis.Success)
                            QMessageBox.information(iface.mainWindow(), "PROCESO", 'Procesamiento finalizado ')
                        else:
                            QMessageBox.information(iface.mainWindow(), "PROCESO",
                                                    'El shape cuenta con una longitud de campos incorrecta, revisa la NORMA ')
                    else:
                        QMessageBox.information(iface.mainWindow(), "PROCESO",
                                                'El shape cuenta con tipos de campos incorrectos, revisa la NORMA ')
                else:
                    QMessageBox.information(iface.mainWindow(), "PROCESO",
                                            'El shape cuenta con una estructura de campos incorrecta, revisa su nombre (cve_ent,cve_mun,cve_loc,id_cat) ')

            else:
                QMessageBox.information(iface.mainWindow(), "PROCESO", 'El archivo no se encuentra en coordenadas geográficas')



            pass