# -*- coding: utf-8 -*-
"""
/***************************************************************************
 shp_to_csv
                                 A QGIS plugin
 Exportar un archivo shape a csv
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-16
        copyright            : (C) 2023 by ioshimar.rodriguez
        email                : ioshimar.rodriguez@inegi.org.mx
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load shp_to_csv class from file shp_to_csv.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shp_to_csv import shp_to_csv
    return shp_to_csv(iface)
