# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportarShapefile
                                 A QGIS plugin
 Exportación de información
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-06-27
        git sha              : $Format:%H$
        copyright            : (C) 2023 by ioshimar.rodriguez
        email                : ioshimar.rodriguez@inegi.org.mx
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from osgeo import ogr
from osgeo import osr
from osgeo import gdal
from qgis._core import QgsFeatureRequest
from shapely.wkt import loads
from qgis.core import QgsVectorLayer, QgsFeature, QgsField, QgsGeometry, QgsPointXY, QgsField, QgsProject, edit
from qgis.utils import iface
from datetime import datetime
import operator
from qgis.core import Qgis
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QDialog
from qgis.core import QgsProject
from PyQt5.QtGui import QIcon, QFileOpenEvent
import geopandas as gpd
import pandas as pd
import os
from pathlib import Path
import requests
import re
from zeep import Client

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ExportarShape_dialog import ExportarShapefileDialog
import os.path


class ExportarShapefile:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ExportarShapefile_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Exportar Shapefile')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ExportarShapefile', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ExportarShape/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Exportar informacion del shp'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Exportar Shapefile'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Selecciona un archivo ", "", '*.shp')
        self.dlg.lineEdit.setText(filename)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ExportarShapefileDialog()
            self.dlg.actionOpen.clicked.connect(self.select_output_file)

        self.dlg.lineEdit.clear()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            filename = self.dlg.lineEdit.text()



            def show_error_message(message):
                # Mostrar cuadro de diálogo con el mensaje de error
                QMessageBox.critical(None, "Error", message)

                # Imprimir el mensaje en la consola
                print(f"Error: {message}")

            def normalize_text(text):
                # Normalizar texto para ignorar diferencias de acentos y convertirlo a minúsculas
                normalized_text = unicodedata.normalize("NFKD", text).casefold()
                return normalized_text

            def validate_shapefile(path):
                try:
                    # Cargamos el Shapefile con geopandas
                    gdf = gpd.read_file(path)

                    # Validamos que el Shapefile contenga geometrías
                    if gdf.empty:
                        raise ValueError("El Shapefile está vacío o no contiene geometrías.")

                    # Validamos los nombres de los campos
                    valid_field_names = ["cve_catast", "folio_real", "cve_edo", "cve_mun", "cve_loc", "id_asent",
                                         "nivel", "tipo_tenen", "tipo_ambit", "uso_suelo", "valor_terr", "valor_cons",
                                         "tipo_insti"]
                    for field_name in valid_field_names:
                        if field_name not in gdf.columns:
                            raise ValueError(f"El campo '{field_name}' no se encuentra en el Shapefile.")

                    # Validamos que los campos "valor_terr" y "valor_cons" sean numéricos
                    numeric_fields = ["valor_terr", "valor_cons"]
                    for field_name in numeric_fields:
                        if not pd.api.types.is_numeric_dtype(gdf[field_name]):
                            raise ValueError(f"El campo '{field_name}' debe ser de tipo numérico.")

                    # Validamos que los demás campos sean de tipo texto o string
                    text_fields = set(gdf.columns) - set(numeric_fields) - {"geometry"}
                    for field_name in text_fields:
                        if not pd.api.types.is_string_dtype(gdf[field_name]):
                            raise ValueError(f"El campo '{field_name}' debe ser de tipo texto o string.")

                    # Validamos los campos cve_edo, cve_mun, cve_loc, id_asent
                    for field_name in ["cve_edo", "cve_mun", "cve_loc", "id_asent"]:
                        if gdf[field_name].isnull().any():
                            raise ValueError(f"El campo '{field_name}' no puede estar vacío.")
                        if field_name == "cve_edo" and ~gdf["cve_edo"].astype(str).str.match(r"^\d{2}$").all():
                            raise ValueError(
                                "El campo 'cve_edo' debe tener un tamaño de dos caracteres y contener solo dígitos.")
                        if field_name == "cve_mun" and ~gdf["cve_mun"].astype(str).str.match(r"^\d{3}$").all():
                            raise ValueError(
                                "El campo 'cve_mun' debe tener un tamaño de tres caracteres y contener solo dígitos.")
                        if field_name == "cve_loc" and ~gdf["cve_loc"].astype(str).str.match(r"^\d{4}$").all():
                            raise ValueError(
                                "El campo 'cve_loc' debe tener un tamaño de cuatro caracteres y contener solo dígitos.")
                        if field_name == "id_asent" and ~gdf["id_asent"].astype(str).str.match(
                                r"^\d{2}\d{3}\d{4}$").all():
                            raise ValueError(
                                "El campo 'id_asent' debe contener nueve dígitos (cve_edo, cve_mun, cve_loc).")

                    # Validamos tipo_tenen, tipo_ambit, tipo_insti
                    valid_tipo_tenen = ["Privada", "Pública"]
                    valid_tipo_ambit = ["Urbano", "Rural", "Semiurbano"]
                    valid_tipo_insti = ["Federal", "Estatal", "Municipal centralizada", "Municipal autónoma"]
                    if ~gdf["tipo_tenen"].isin(valid_tipo_tenen).all():
                        raise ValueError("El campo 'tipo_tenen' solo puede contener 'Privada' o 'Pública'.")
                    if ~gdf["tipo_ambit"].isin(valid_tipo_ambit).all():
                        raise ValueError("El campo 'tipo_ambit' solo puede contener 'Urbano', 'Rural' o 'Semiurbano'.")
                    if ~gdf["tipo_insti"].isin(valid_tipo_insti).all():
                        raise ValueError(
                            "El campo 'tipo_insti' solo puede contener 'Federal', 'Estatal', 'Municipal centralizada' o 'Municipal autónoma'.")

                    # Mostramos los nombres de los campos y sus tipos
                    print("Nombres de los campos y sus tipos:")
                    for field_name, field_type in zip(gdf.columns, gdf.dtypes):
                        print(f"{field_name}: {field_type}")

                    print("Validación exitosa: El Shapefile contiene geometrías y los campos son válidos.")

                    client = Client('http://10.107.12.36:8080/web_serv/insertUE?wsdl')

                    # path = 'D:/RESPALDO/PRUEBAS_RNIC/rnic.shp'

                    dataSource1 = ogr.Open(path, 1)

                    layer = dataSource1.GetLayer()
                    layerDefinition = layer.GetLayerDefn()

                    for campos in layer:
                        geom = campos.GetGeometryRef()
                        # print(geom)
                        cve_catast = campos.GetField("cve_catast")
                        folio_real = campos.GetField("folio_real")
                        cve_edo = campos.GetField("cve_edo")
                        cve_mun = campos.GetField("cve_mun")
                        cve_loc = campos.GetField("cve_loc")
                        id_asent = campos.GetField("id_asent")
                        nivel = campos.GetField("nivel")
                        tipo_tenen = campos.GetField("tipo_tenen")
                        tipo_ambit = campos.GetField("tipo_ambit")
                        uso_suelo = campos.GetField("uso_suelo")
                        valor_terr = campos.GetField("valor_terr")
                        valor_cons = campos.GetField("valor_cons")
                        tipo_insti = campos.GetField("tipo_insti")
                        result = client.service.insertar(cve_catast, folio_real, cve_edo, cve_mun, cve_loc, id_asent,
                                                         nivel, tipo_tenen, tipo_ambit, uso_suelo, valor_terr,
                                                         valor_cons, tipo_insti, geom)
                        # print(geom)

                    QMessageBox.information(iface.mainWindow(), "PROCESO", 'Envío finalizado ')

                except ValueError as e:
                    show_error_message(str(e))
                except Exception as e:
                    print(f"Error: {e}")

            # Ruta del Shapefile a validar
            path = '' + filename + ''

            # Llamamos a la función para validar el Shapefile
            validate_shapefile(path)

            pass
