# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importar_shape_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportarShapeDialogBase(object):
    def setupUi(self, ImportarShapeDialogBase):
        ImportarShapeDialogBase.setObjectName("ImportarShapeDialogBase")
        ImportarShapeDialogBase.resize(395, 165)
        self.button_box = QtWidgets.QDialogButtonBox(ImportarShapeDialogBase)
        self.button_box.setGeometry(QtCore.QRect(0, 100, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.actionOpen = QtWidgets.QToolButton(ImportarShapeDialogBase)
        self.actionOpen.setGeometry(QtCore.QRect(270, 60, 71, 19))
        self.actionOpen.setObjectName("actionOpen")
        self.lineEdit = QtWidgets.QLineEdit(ImportarShapeDialogBase)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(ImportarShapeDialogBase)
        self.label.setGeometry(QtCore.QRect(40, 20, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.actionOpen.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.button_box.raise_()

        self.retranslateUi(ImportarShapeDialogBase)
        self.button_box.accepted.connect(ImportarShapeDialogBase.accept)
        self.button_box.rejected.connect(ImportarShapeDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportarShapeDialogBase)

    def retranslateUi(self, ImportarShapeDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ImportarShapeDialogBase.setWindowTitle(_translate("ImportarShapeDialogBase", "Importar Shapefile"))
        self.actionOpen.setText(_translate("ImportarShapeDialogBase", "Buscar ..."))
        self.label.setText(_translate("ImportarShapeDialogBase", "Selecciona tú archivo a enviar:"))
