# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CargarVectorial
                                 A QGIS plugin
 Carga de informacion vectorial
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-09
        copyright            : (C) 2024 by ioshimar.rodriguez
        email                : ioshimar.rodriguez@inegi.org.mx
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CargarVectorial class from file CargarVectorial.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CargarVectorial import CargarVectorial
    return CargarVectorial(iface)
