# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CargarVectorial
                                 A QGIS plugin
 Carga de informacion vectorial
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-09
        git sha              : $Format:%H$
        copyright            : (C) 2024 by ioshimar.rodriguez
        email                : ioshimar.rodriguez@inegi.org.mx
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsVectorLayer, QgsProject, QgsSimpleLineSymbolLayer, QgsSimpleFillSymbolLayer, QgsSymbol
from qgis.core import QgsSymbolLayerUtils
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt.QtCore import QTimer

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .CargarVectorial_dialog import CargarVectorialDialog
import os.path


class CargarVectorial:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CargarVectorial_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Cargar Vectorial')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):

        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CargarVectorial', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):


        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/CargarVectorial/icon.png'
        self.action = self.add_action(
            icon_path,
            text=self.tr(u'Detectar vectorial'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Agrupar el plugin en el menú personalizado
        self.menu = self.tr(u'Análisis de información')
        self.iface.addPluginToMenu(self.menu, self.action)

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Cargar Vectorial'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Crear una ventana emergente sin botones
        msg_box = QMessageBox(self.iface.mainWindow())
        msg_box.setWindowTitle("Detectando vectores....")

        # Agregar texto al mensaje
        msg_box.setText("Espere mientras se detectan los vectores...")

        # Ocultar los botones estándar
        msg_box.setStandardButtons(QMessageBox.NoButton)

        # Mostrar la ventana emergente
        msg_box.show()

        # Configurar temporizador para cerrar la ventana después de 10 segundos
        timer = QTimer(self.iface.mainWindow())
        timer.timeout.connect(msg_box.accept)  # Usar accept para cerrar la ventana
        timer.timeout.connect(self.load_layers)  # Conectar la carga de capas después de cerrar la ventana
        timer.setSingleShot(True)  # Configurar el temporizador para ejecutarse solo una vez
        timer.start(10000)  # 10000 milisegundos = 10 segundo

    def load_layers(self):
        """Método para cargar las capas después de 10 segundos"""
        ruta_capas = r'D:\PLUGIN_CARGA_CAPAS'
        ruta_manzanas = 'manzanas_corte.shp'
        ruta_vialidades = 'vialidades_corte.shp'

        # Cargar capa de manzanas
        capa_manzanas = QgsVectorLayer(ruta_capas + '\\' + ruta_manzanas, 'Manzanas', 'ogr')
        if not capa_manzanas.isValid():
            print('Error al cargar la capa de manzanas')
        else:
            # Establecer símbolo para polígonos con contorno café
            simbolo_manzanas = QgsSymbol.defaultSymbol(capa_manzanas.geometryType())

            if simbolo_manzanas.symbolLayerCount() > 0:
                symbol_layer = simbolo_manzanas.symbolLayer(0)
                if isinstance(symbol_layer, QgsSimpleFillSymbolLayer):
                    # symbol_layer.setStrokeColor(QgsSymbolLayerUtils.parseColor('rgb(139, 69, 19)'))
                    symbol_layer.setStrokeColor(QgsSymbolLayerUtils.parseColor('blue'))
                    symbol_layer.setStrokeWidth(1)
                    symbol_layer.setColor(QgsSymbolLayerUtils.parseColor('rgba(0,0,0,0)'))  # Relleno transparente

            capa_manzanas.renderer().setSymbol(simbolo_manzanas)

            # Agregar capa al proyecto
            QgsProject.instance().addMapLayer(capa_manzanas)

        # Cargar capa de vialidades
        capa_vialidades = QgsVectorLayer(ruta_capas + '\\' + ruta_vialidades, 'Vialidades', 'ogr')
        if not capa_vialidades.isValid():
            print('Error al cargar la capa de vialidades')
        else:
            # Establecer símbolo para líneas con grosor rojo de 1 mm
            simbolo_vialidades = QgsSymbol.defaultSymbol(capa_vialidades.geometryType())

            if simbolo_vialidades.symbolLayerCount() > 0:
                symbol_layer = simbolo_vialidades.symbolLayer(0)
                if isinstance(symbol_layer, QgsSimpleLineSymbolLayer):
                    symbol_layer.setColor(QgsSymbolLayerUtils.parseColor('red'))
                    symbol_layer.setWidth(1)

            capa_vialidades.renderer().setSymbol(simbolo_vialidades)

            # Agregar capa al proyecto
            QgsProject.instance().addMapLayer(capa_vialidades)

        print('Capas cargadas exitosamente.')
